cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'), 
    path('history/', views.orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/',views.orderDetail.as_view(),name='order_detail'),
]

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name='search_app'

urlpatterns = [
    path('', SearchResultsListView.as_view(), name='searchResult'),
] 

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [ 
    path('', views.prod_list, name = 'all_products'), 
    path('<uuid:category_id>/', views.prod_list, name = 'products_by_category'), 
    path('<uuid:category_id>/<uuid:product_id>/', views.product_detail, name = 'product_detail'),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('',include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/',include('cart.urls')),
    path('order/',include('order.urls')),
    path('voucher/', include('vouchers.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models

# Create your models here.
import uuid
from django.urls import reverse

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    image = models.ImageField(upload_to = 'category', blank=True) 

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])

    def __str__(self):
        return self.name 

class Product(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank = True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to = 'product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank = True, null= True)
    updated = models.DateTimeField(auto_now=True, blank = True, null= True)
    
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.id, self.id])


    def __str__(self):
        return self.name

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product 
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here. 
def prod_list(request, category_id=None): 
    category = None 
    products = Product.objects.filter(available=True) 
    if category_id:
        category = get_object_or_404(Category, id=category_id)
        products = Product.objects.filter(category = category, available=True) 
    
    paginator = Paginator(products, 6)
    try:
        page = int(request.GET.get('Page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage): 
        products = paginator.page(paginator.num_pages)
    
    return  render(request,'shop/category.html',{'category':category, 'prods':products}) 
    
def product_detail(request, category_id, product_id):
    product = get_object_or_404(Product, category_id=category_id, id=product_id)
    return render(request, 'shop/product.html', {'product':product})

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head> 
        <meta charset="utf-8"> 
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
        <link rel="stylesheet" href="{% static 'css/custom.css' %}"> 
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        rel="stylesheet" integrity="sha384-
        Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
        crossorigin="anonymous"> 
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
        <meta name="description" content="{% block metadescription %}{% endblock %}"> 
        <title>{% block title %}{% endblock %}</title>  
</head>
<body> 
    <div class="container"> 
        <div class="container-fluid bg-light navbar-fixed-top my_top_navbar_div">
            {% include 'top-navbar.html' %}
        </div>
        {% include 'header.html' %}
        {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}

        {% include 'footer.html' %} 

    </div>
        
        
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"crossorigin="anonymous"></script>


</body>
</html>

shop/templates/footer.html
<div class = "footer navbar-fixed-bottom my-footer">
    <p class = "text-center">&copy; Sport Spree.</p>
</div>

shop/templates/header.html
{% load static %}
<header>
    <div style="text-align: center;"> 
        <a href="{% url 'shop:all_products' %}"> 
        <img src="{% static 'images/Logo.png ' %}" alt="Sport Spree Store"></a>

    </div>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>

       <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">shop</a>

    
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                 <li><a class="dropdown-item" href="{% url 'shop:all_products' %}">All Products</a></li>
                    {% for cat in links %}
                        <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                    {% endfor %}
                 </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Your Cart</a>
                 </li> 
                 {% if item_count > 0 %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i 
                      class="fas fa-shopping-cart">({{item_count}})</i></a>
                  </li>
                  {% endif %}           

                </ul>
                <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
                 <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                 <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
        </div>
    </div>
</nav>

shop/templates/top-navbar.html
<div class="container">
    <div class="my_custom_menu">
        <ul>
            {% if user.is_authenticated %}
            <li>
                Welcome, <a href="#" class="dropdown-toggle" data-bs-toggle="dropdown" 
                aria-haspopup="true" aria-expanded="false">{{ user.username }} 
                <i class="fas fa-user-circle"></i></a>
                <div class="dropdown-menu dropdown-menu-right"> 
                    <a href="{% url 'order:order_history' %}" class="dropdown-item">Order Hostory</a>
                </div>
            </li>
            <li>
                <a href="{% url 'logout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
            </li>
            <li>
                <a href="{% url 'login' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
            </li>
            {% endif %}
        </ul>
        
    </div>
</div>